KNN Assignment

In [4]:
from scipy.io import arff
import pandas as pd
import math
import operator

In [5]:
data = arff.loadarff('trainProdSelection.arff')
training_set = pd.DataFrame(data[0])

data = arff.loadarff('testProdSelection.arff')
testing_set = pd.DataFrame(data[0])
training_set.head()

         Type        LifeStyle  Vacation  eCredit  salary  property  label
0  b'student'  b'spend>saving'       6.0     40.0   13.62    3.2804  b'C1'
1  b'student'  b'spend>saving'      11.0     21.0   15.32    2.0232  b'C1'
2  b'student'  b'spend>saving'       7.0     64.0   16.55    3.1202  b'C1'
3  b'student'  b'spend>saving'       3.0     47.0   15.71    3.4022  b'C1'
4  b'student'  b'spend>saving'      15.0     10.0   16.96    2.2825  b'C1'

In [6]:
testing_set.head()

           Type         LifeStyle  Vacation  eCredit   salary  property  label
0    b'student'   b'spend<saving'      12.0     19.0  14.7900    3.7697  b'C1'
1    b'student'  b'spend>>saving'      29.0     10.0  16.1900    2.4839  b'C1'
2    b'student'  b'spend<<saving'      28.0     60.0  15.4600    1.1885  b'C1'
3   b'engineer'   b'spend>saving'      15.0     41.0  21.2600    1.4379  b'C1'
4  b'librarian'   b'spend<saving'       2.0      9.0  19.7207    0.6913  b'C1'

In [7]:
pd.DataFrame(data[0]).dtypes

Type          object
LifeStyle     object
Vacation     float64
eCredit      float64
salary       float64
property     float64
label         object
dtype: object

Format data

In [8]:
training_set.Type = training_set.Type.str.decode("UTF-8")
training_set.LifeStyle = training_set.LifeStyle.str.decode("UTF-8")
training_set.label = training_set.label.str.decode("UTF-8")

In [9]:
minValue = training_set.Vacation.min()
maxValue = training_set.Vacation.max()
training_set.Vacation = training_set.Vacation.apply(lambda x:(x-minValue)/(maxValue-minValue))

minValue = training_set.eCredit.min()
maxValue = training_set.eCredit.max()
training_set.eCredit = training_set.eCredit.apply(lambda x:(x-minValue)/(maxValue-minValue))

minValue = training_set.salary.min()
maxValue = training_set.salary.max()
training_set.salary = training_set.salary.apply(lambda x:(x-minValue)/(maxValue-minValue))

minValue = training_set.property.min()
maxValue = training_set.property.max()
training_set.property = training_set.property.apply(lambda x:(x-minValue)/(maxValue-minValue))

In [10]:
testing_set.Type=testing_set.Type.str.decode("UTF-8")
testing_set.LifeStyle=testing_set.LifeStyle.str.decode("UTF-8")
testing_set.label=testing_set.label.str.decode("UTF-8")

In [11]:
minValue = testing_set.Vacation.min()
maxValue = testing_set.Vacation.max()
testing_set.Vacation = testing_set.Vacation.apply(lambda x:(x-minValue)/(maxValue-minValue))

minValue = testing_set.eCredit.min()
maxValue = testing_set.eCredit.max()
testing_set.eCredit = testing_set.eCredit.apply(lambda x:(x-minValue)/(maxValue-minValue))

minValue = testing_set.salary.min()
maxValue = testing_set.salary.max()
testing_set.salary = testing_set.salary.apply(lambda x:(x-minValue)/(maxValue-minValue))

minValue = testing_set.property.min()
maxValue = testing_set.property.max()
testing_set.property = testing_set.property.apply(lambda x:(x-minValue)/(maxValue-minValue))

KNN:

In [58]:
def euclideanDistance(instance1, instance2, length):
    distance = 0
    for i in range(2):        
        if (instance1[i]==instance2[i]):
            distance =distance+1
        else:
            distance+=0
            #print(distance)
    for x in range(2,length):
        distance += pow((instance1[x] - instance2[x]), 2)
    return math.sqrt(distance)
 
def getNeighbors(trainingSet, testInstance, k):
    distances = []
    length = len(testInstance)-1
    for x in range(len(trainingSet)):
        dist = euclideanDistance(testInstance, trainingSet[x], length)
        #print(dist)
        distances.append((trainingSet[x], dist))
        #print(distances)
    distances.sort(key=operator.itemgetter(1))
    neighbors = []
    for x in range(k):
        neighbors.append(distances[x])
        #print(neighbors)
    return neighbors
 
def getResponse(neighbors):
#     print(neighbors)
    classVotes = {}
#     print(classVotes)
    for x in range(len(neighbors)):
        #print(neighbors)
#       print(neighbors[x][1])
        response = neighbors[x][0][-1]
        if response in classVotes:
            classVotes[response] += 1
        else:
            classVotes[response] = 1
#     print(classVotes[response])
    sortedVotes = sorted(classVotes.items(), key=operator.itemgetter(1), reverse=True)
    return sortedVotes[0][0]
 
def getAccuracy(testSet, predictions):
    correct = 0
    for x in range(len(testSet)):
        if testSet[x][-1] == predictions[x]:
            correct += 1
    return (correct/float(len(testSet))) * 100.0

In [59]:
def knn(k):
    predictions=[]
    for x in range(len(testing_set)):
        neighbors = getNeighbors(training_set.values, testing_set.values[x], k)
        result = getResponse(neighbors)
        #print(result)
        predictions.append(result)
        #print(neighbors)
    accuracy = getAccuracy(testing_set.values, predictions)
    print('Accuracy: ' + repr(accuracy) + '%')

FUNCTION TO CHECK OVER MULTIPLE K VALUES

In [62]:
def red():
    i=1
    while(i<180):
        print('i='+str(i))
        knn(i)
        i+=2

In [63]:
red()

i=1
Accuracy: 19.047619047619047%
i=3
Accuracy: 23.809523809523807%
i=5
Accuracy: 19.047619047619047%
i=7
Accuracy: 14.285714285714285%
i=9
Accuracy: 19.047619047619047%
i=11
Accuracy: 19.047619047619047%
i=13
Accuracy: 23.809523809523807%
i=15
Accuracy: 23.809523809523807%
i=17
Accuracy: 28.57142857142857%
i=19
Accuracy: 28.57142857142857%
i=21
Accuracy: 28.57142857142857%
i=23
Accuracy: 28.57142857142857%
i=25
Accuracy: 28.57142857142857%
i=27
Accuracy: 28.57142857142857%
i=29
Accuracy: 28.57142857142857%
i=31
Accuracy: 28.57142857142857%
i=33
Accuracy: 28.57142857142857%
i=35
Accuracy: 23.809523809523807%
i=37
Accuracy: 23.809523809523807%
i=39
Accuracy: 23.809523809523807%
i=41
Accuracy: 23.809523809523807%
i=43
Accuracy: 19.047619047619047%
i=45
Accuracy: 19.047619047619047%
i=47
Accuracy: 14.285714285714285%
i=49
Accuracy: 19.047619047619047%
i=51
Accuracy: 14.285714285714285%
i=53
Accuracy: 19.047619047619047%
i=55
Accuracy: 9.523809523809524%
i=57
Accuracy: 9.523809523809524%
i=59
Accuracy: 9.523809523809524%
i=61
Accuracy: 9.523809523809524%
i=63
Accuracy: 9.523809523809524%
i=65
Accuracy: 9.523809523809524%
i=67
Accuracy: 9.523809523809524%
i=69
Accuracy: 14.285714285714285%
i=71
Accuracy: 14.285714285714285%
i=73
Accuracy: 14.285714285714285%
i=75
Accuracy: 14.285714285714285%
i=77
Accuracy: 14.285714285714285%
i=79
Accuracy: 14.285714285714285%
i=81
Accuracy: 14.285714285714285%
i=83
Accuracy: 14.285714285714285%
i=85
Accuracy: 14.285714285714285%
i=87
Accuracy: 14.285714285714285%
i=89
Accuracy: 19.047619047619047%
i=91
Accuracy: 19.047619047619047%
i=93
Accuracy: 19.047619047619047%
i=95
Accuracy: 23.809523809523807%
i=97
Accuracy: 23.809523809523807%
i=99
Accuracy: 23.809523809523807%
i=101
Accuracy: 23.809523809523807%
i=103
Accuracy: 23.809523809523807%
i=105
Accuracy: 23.809523809523807%
i=107
Accuracy: 23.809523809523807%
i=109
Accuracy: 23.809523809523807%
i=111
Accuracy: 23.809523809523807%
i=113
Accuracy: 23.809523809523807%
i=115
Accuracy: 23.809523809523807%
i=117
Accuracy: 23.809523809523807%
i=119
Accuracy: 19.047619047619047%
i=121
Accuracy: 14.285714285714285%
i=123
Accuracy: 14.285714285714285%
i=125
Accuracy: 9.523809523809524%
i=127
Accuracy: 9.523809523809524%
i=129
Accuracy: 9.523809523809524%
i=131
Accuracy: 9.523809523809524%
i=133
Accuracy: 9.523809523809524%
i=135
Accuracy: 9.523809523809524%
i=137
Accuracy: 9.523809523809524%
i=139
Accuracy: 9.523809523809524%
i=141
Accuracy: 14.285714285714285%
i=143
Accuracy: 9.523809523809524%
i=145
Accuracy: 9.523809523809524%
i=147
Accuracy: 9.523809523809524%
i=149
Accuracy: 4.761904761904762%
i=151
Accuracy: 4.761904761904762%
i=153
Accuracy: 4.761904761904762%
i=155
Accuracy: 4.761904761904762%
i=157
Accuracy: 4.761904761904762%
i=159
Accuracy: 0.0%
i=161
Accuracy: 0.0%
i=163
Accuracy: 0.0%
i=165
Accuracy: 0.0%
i=167
Accuracy: 0.0%
i=169
Accuracy: 0.0%
i=171
Accuracy: 0.0%
i=173
Accuracy: 0.0%
i=175
Accuracy: 0.0%
i=177
Accuracy: 0.0%
i=179
Accuracy: 0.0%